services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financial_api_development_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/financial_api_development_db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0"]

volumes:
  db_data:
